//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Turnos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class profesional
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public profesional()
        {
            this.turnoes = new HashSet<turno>();
        }
    
        public int idProfesional { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public decimal dni { get; set; }
        public Nullable<decimal> telefono { get; set; }
        public string mail { get; set; }
        public string matricula { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<turno> turnoes { get; set; }
    }
}
