//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Turnos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoNT1Entities1 : DbContext
    {
        public ProyectoNT1Entities1()
            : base("name=ProyectoNT1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<obraSocial> obraSocials { get; set; }
        public virtual DbSet<paciente> pacientes { get; set; }
        public virtual DbSet<profesional> profesionals { get; set; }
        public virtual DbSet<turno> turnoes { get; set; }
    }
}
