//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Turnos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class turno
    {
        public int idPaciente { get; set; }
        public int idProfesional { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual paciente paciente { get; set; }
        public virtual profesional profesional { get; set; }
    }
}
